### ISSUE TITLE
It's impossible to portably set \g_luabridge_method_int before loading the package?

### ISSUE THREAD

**Issue by user202729** [Witiko/lt3luabridge#10]
Because the constants e.g. `\c_luabridge_method_write_eighteen_int` does not exist at that time. Unless we assume them to be equal to 0/1/2 respectively, but that doesn't seem portable.

Would be simpler to simply use package options.

(side note, when I hard code it to use write18  method on LuaTeX it doesn't actually work, not sure why. But better use  expl3's `\c_sys_shell_escape_int` than some engine-specific primitive to detect shell-escape level.

**Comment by Witiko** [comment]
> When I hard code it to use write18 method on LuaTeX it doesn't actually work, not sure why

In LuaTeX, `\write18` is unavailable and it is therefore necessary to use `os.execute()` from Lua.
