### ISSUE TITLE
The final "end" is not separated from the code with a space

### ISSUE THREAD

**Issue by user202729** [Witiko/lt3luabridge#11]
As mentioned in the title.

For example if you execute `x=1`, which is independently valid Lua code, the resulting code will contain e.g. `1end` which is invalid.

**Comment by Witiko** [comment]
Thank you for the report.

**Comment by Witiko** [comment]
I don't see how the final `end` would not be separated. There is an explicit `~` between `\l_tmpa_tl` and `end`:

https://github.com/Witiko/lt3luabridge/blob/afcb9ed531de7f142f6181ec890e1abcc7861400/lt3luabridge.dtx#L508-L512

Closing the report as invalid.

**Comment by user202729** [comment]
Common TeX trap, in `\l_tmpa_tl~` the `~` despite what it looks like will be absorbed by the control sequence name.

Just try executing `x=1` with the package.

**Comment by Witiko** [comment]
Ok, let's test this.

**Comment by Witiko** [comment]
@user202729 Should be fixed by #14. Thanks again for the report and sorry for incorrectly dismissing it.
