### ISSUE TITLE
Typo in the README

### ISSUE THREAD

**Issue by dbitouze** [Witiko/lt3luabridge#7]
The README currently provides the following example:
```latex
\documentclass{standalone}
\usepackage{l3luabridge}
\begin{document}
$ 1 + 2 = \luabridgeExecute{ print(1 + 2) } $
\end{document}
```
where `\usepackage{l3luabridge}` should be `\usepackage{lt3luabridge}`.

**Comment by Witiko** [comment]
@dbitouze Thank you, I fixed this in a906ee54a3d2386589334366446d91c95e3d3b91.
